import { useState, useEffect } from "react";
import { useLocation } from "wouter";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Loader2, CheckCircle2, XCircle, AlertTriangle, ChevronDown, ChevronUp,
  ShieldCheck, Clock, Download, TrendingUp, FileText, Filter, Square, CheckSquare,
  Plus, Send, BookOpen, Printer, Eye, Building2, X,
} from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { useLancingAuth } from "@/hooks/use-lancing-auth";
import { auth } from "@/lib/firebase";

async function apiFetch(url: string, init: RequestInit = {}) {
  const token = await auth.currentUser?.getIdToken();
  return fetch(url, {
    ...init,
    headers: { "Content-Type": "application/json", ...(init.headers || {}), ...(token ? { Authorization: `Bearer ${token}` } : {}) },
  });
}

const COE_STATUS_STYLES: Record<string, string> = {
  pending_coe: "bg-amber-50 text-amber-700 border-amber-200",
  approved: "bg-green-50 text-green-700 border-green-200",
  flagged: "bg-red-50 text-red-700 border-red-200",
  retake_required: "bg-purple-50 text-purple-700 border-purple-200",
  proof_requested: "bg-blue-50 text-blue-700 border-blue-200",
};
const COE_STATUS_LABELS: Record<string, string> = {
  pending_coe: "Pending Verification",
  approved: "Approved ✅",
  flagged: "Flagged ⚠️",
  retake_required: "Retake Required",
  proof_requested: "Docs Requested",
};

type Tab = "pending" | "approved" | "flagged" | "drives";

const EMPTY_DRIVE = { title: "", company: "", date: "", min_score: "", min_cgpa: "", branch_filter: "" };

function printStudentPage(student: any) {
  const w = window.open("", "_blank", "width=800,height=700");
  if (!w) return;
  const skills = Object.entries(student.skills_summary || {}).map(([skill, v]: [string, any]) => {
    const isObj = v && typeof v === "object";
    return `<tr><td>${skill}</td><td>${isObj ? (v.status || "-").replace(/_/g, " ") : "-"}</td><td>${isObj ? `${v.credits_earned || 0}/${v.credits_total || 0}` : "-"}</td></tr>`;
  }).join("");
  w.document.write(`<!DOCTYPE html><html><head><title>Transcript — ${student.name || student.email}</title>
<style>body{font-family:Arial,sans-serif;max-width:680px;margin:2rem auto;color:#111}h1{font-size:1.3rem;margin-bottom:0.3rem}p{margin:0.2rem 0;font-size:13px}table{width:100%;border-collapse:collapse;margin-top:1rem;font-size:12px}th{background:#f0f0f0;padding:6px 10px;text-align:left;border:1px solid #ccc}td{padding:5px 10px;border:1px solid #ddd}.meta{margin-top:0.8rem;padding:0.6rem 1rem;background:#f7f7f7;border-radius:6px;font-size:12px}.footer{margin-top:2rem;font-size:11px;color:#888}</style>
</head><body>
<h1>Placement Transcript</h1>
<div class="meta">
<p><strong>Name:</strong> ${student.name || student.email}</p>
<p><strong>Branch:</strong> ${student.branch || "—"}</p>
<p><strong>CGPA (self-reported):</strong> ${student.cgpa_self_reported || "—"}</p>
<p><strong>Credits Earned:</strong> ${student.credits_earned || 0} / ${student.credits_total || 0}</p>
<p><strong>Readiness Score:</strong> ${student.overall_score || 0}%</p>
<p><strong>Coding Arena Score:</strong> ${student.coding_score != null ? `${student.coding_score}%` : "—"}</p>
<p><strong>COE Status:</strong> ${COE_STATUS_LABELS[student.coe_status] || student.coe_status}</p>
<p><strong>Flags:</strong> ${student.flag_count || 0}</p>
</div>
${skills ? `<table><thead><tr><th>Skill</th><th>Status</th><th>Credits</th></tr></thead><tbody>${skills}</tbody></table>` : ""}
<div class="footer">Generated by StudentXchange COE Portal · ADYPU · ${new Date().toLocaleDateString()}</div>
<script>window.print();</script></body></html>`);
  w.document.close();
}

export default function COEDashboard() {
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const { user, isAuthenticated, isLoading: authLoading } = useLancingAuth();

  const [activeTab, setActiveTab] = useState<Tab>("pending");
  const [students, setStudents] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [expandedRow, setExpandedRow] = useState<string | null>(null);
  const [verifiedCGPA, setVerifiedCGPA] = useState<Record<string, string>>({});
  const [acting, setActing] = useState<string | null>(null);
  const [funnel, setFunnel] = useState<{ enrolled: number; started: number; l1_passed: number; l2_passed: number; l3_passed: number; eligible: number } | null>(null);
  const [selectedUids, setSelectedUids] = useState<Set<string>>(new Set());
  const [bulkReason, setBulkReason] = useState("");

  // Filters
  const [filterBranch, setFilterBranch] = useState("");
  const [filterMinScore, setFilterMinScore] = useState("");
  const [filterYear, setFilterYear] = useState("");
  const [filterTargetRole, setFilterTargetRole] = useState("");
  const [filterCoeVerified, setFilterCoeVerified] = useState(false);
  const [filterMinSkills, setFilterMinSkills] = useState("");

  // Flagged assessments (T007)
  const [flaggedAttempts, setFlaggedAttempts] = useState<any[]>([]);
  const [flaggedLoading, setFlaggedLoading] = useState(false);

  // Drives (T006)
  const [drives, setDrives] = useState<any[]>([]);
  const [drivesLoading, setDrivesLoading] = useState(false);
  const [showDriveForm, setShowDriveForm] = useState(false);
  const [driveForm, setDriveForm] = useState(EMPTY_DRIVE);
  const [driveCreating, setDriveCreating] = useState(false);
  const [inviting, setInviting] = useState<string | null>(null);

  // Credit ledger per student (T007)
  const [ledgerData, setLedgerData] = useState<Record<string, any>>({});
  const [ledgerLoading, setLedgerLoading] = useState<Record<string, boolean>>({});

  useEffect(() => {
    if (authLoading) return;
    if (!isAuthenticated || !user) setLocation("/lancing/login");
  }, [authLoading, isAuthenticated, user]);

  useEffect(() => {
    if (!user) return;
    loadStudents();
    loadFunnel();
  }, [user]);

  useEffect(() => {
    if (activeTab === "flagged" && user) loadFlaggedAttempts();
    if (activeTab === "drives" && user) loadDrives();
  }, [activeTab, user]);

  async function loadStudents() {
    setLoading(true);
    try {
      const r = await apiFetch("/api/placement/shortlist");
      if (r.ok) setStudents((await r.json()).students || []);
    } catch {}
    setLoading(false);
  }

  async function loadFunnel() {
    try {
      const r = await apiFetch("/api/placement/funnel-stats");
      if (r.ok) setFunnel(await r.json());
    } catch {}
  }

  async function loadFlaggedAttempts() {
    setFlaggedLoading(true);
    try {
      const r = await apiFetch("/api/placement/flagged-attempts");
      if (r.ok) setFlaggedAttempts((await r.json()).attempts || []);
    } catch {}
    setFlaggedLoading(false);
  }

  async function loadDrives() {
    setDrivesLoading(true);
    try {
      const r = await apiFetch("/api/placement/drives");
      if (r.ok) setDrives((await r.json()).drives || []);
    } catch {}
    setDrivesLoading(false);
  }

  async function loadLedger(uid: string) {
    setLedgerLoading(prev => ({ ...prev, [uid]: true }));
    try {
      const r = await apiFetch(`/api/placement/transcript/${uid}`);
      if (r.ok) {
        const data = await r.json();
        setLedgerData(prev => ({ ...prev, [uid]: data }));
      }
    } catch {}
    setLedgerLoading(prev => ({ ...prev, [uid]: false }));
  }

  async function performBulkAction(action: "approve" | "flag" | "request_proof") {
    if (selectedUids.size === 0) { toast({ title: "No students selected", variant: "destructive" }); return; }
    if ((action === "flag" || action === "request_proof") && !bulkReason.trim()) {
      toast({ title: "Reason required", variant: "destructive" }); return;
    }
    setActing("bulk");
    try {
      const r = await apiFetch("/api/placement/coe-bulk-action", {
        method: "POST",
        body: JSON.stringify({ studentUids: Array.from(selectedUids), action, reason: bulkReason.trim() || undefined, university: "ADYPU", batch: "2025" }),
      });
      if (!r.ok) throw new Error("Bulk action failed");
      const data = await r.json();
      toast({ title: "Bulk action complete", description: `${data.count} students updated.` });
      setSelectedUids(new Set()); setBulkReason("");
      await loadStudents(); await loadFunnel();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setActing(null); }
  }

  async function performAction(studentUid: string, action: string) {
    setActing(studentUid + action);
    try {
      const r = await apiFetch("/api/placement/coe-action", {
        method: "POST",
        body: JSON.stringify({ studentUid, action, verified_cgpa: verifiedCGPA[studentUid], university: "ADYPU", batch: "2025" }),
      });
      if (!r.ok) throw new Error("Action failed");
      toast({ title: "Action recorded" });
      await loadStudents(); setExpandedRow(null);
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setActing(null); }
  }

  async function resolveFlagged(uid: string, attemptId: string, action: "approve_credits" | "dismiss") {
    setActing(`flagged_${attemptId}_${action}`);
    try {
      const r = await apiFetch("/api/placement/resolve-flagged-attempt", {
        method: "POST",
        body: JSON.stringify({ uid, attemptId, action }),
      });
      if (!r.ok) throw new Error("Failed");
      toast({ title: action === "approve_credits" ? "Credits approved and awarded" : "Review dismissed" });
      await loadFlaggedAttempts();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setActing(null); }
  }

  async function createDrive() {
    if (!driveForm.title.trim() || !driveForm.company.trim()) {
      toast({ title: "Title and company are required", variant: "destructive" }); return;
    }
    setDriveCreating(true);
    try {
      const r = await apiFetch("/api/placement/drives", {
        method: "POST",
        body: JSON.stringify({ ...driveForm, university: "ADYPU", batch: "2025" }),
      });
      if (!r.ok) throw new Error("Failed");
      const data = await r.json();
      toast({ title: "Drive created", description: `${data.shortlisted_count} students auto-shortlisted.` });
      setDriveForm(EMPTY_DRIVE); setShowDriveForm(false);
      await loadDrives();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setDriveCreating(false); }
  }

  async function inviteDrive(driveId: string) {
    setInviting(driveId);
    try {
      const r = await apiFetch(`/api/placement/drives/${driveId}/invite`, {
        method: "POST",
        body: JSON.stringify({ university: "ADYPU", batch: "2025" }),
      });
      if (!r.ok) throw new Error("Failed");
      const data = await r.json();
      toast({ title: "Invitations sent", description: `${data.invited} students notified.` });
      await loadDrives();
    } catch (err: any) {
      toast({ title: "Failed", description: err.message, variant: "destructive" });
    } finally { setInviting(null); }
  }

  function exportCSV(list: any[]) {
    const rows = list.map(s => {
      const skillsStr = Object.entries(s.skills_summary || {}).map(([k, v]: [string, any]) => {
        if (v && typeof v === "object") return `${k}:${v.status || "n/a"}(${v.credits_earned || 0}/${v.credits_total || 0}cr)`;
        return `${k}:${v}%`;
      }).join("; ");
      return [s.name || s.email, s.branch, s.cgpa_self_reported, s.year || "", s.target_role || "",
        `${s.credits_earned || 0}/${s.credits_total || 0}`, `${s.overall_score}%`,
        s.coding_score != null ? `${s.coding_score}%` : "",
        skillsStr, s.flag_count || 0, s.coe_status].join(",");
    });
    const csv = ["Name,Branch,CGPA,Year,Target Role,Credits Earned,Readiness %,Coding %,Skills Detail,Flags,COE Status", ...rows].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url;
    a.download = `coe_shortlist_${new Date().toISOString().split("T")[0]}.csv`;
    a.click(); URL.revokeObjectURL(url);
  }

  function toggleSelect(uid: string) {
    setSelectedUids(prev => { const next = new Set(prev); if (next.has(uid)) next.delete(uid); else next.add(uid); return next; });
  }

  if (authLoading || (loading && activeTab !== "flagged" && activeTab !== "drives")) {
    return <div className="min-h-screen bg-gray-50 flex items-center justify-center"><Loader2 className="w-8 h-8 text-indigo-500 animate-spin" /></div>;
  }

  const pending = students.filter(s => s.coe_status === "pending_coe");
  const approved = students.filter(s => s.coe_status === "approved");
  const baseList = activeTab === "pending" ? pending : approved;
  const activeList = baseList.filter(s => {
    if (filterBranch && !(s.branch || "").toLowerCase().includes(filterBranch.toLowerCase())) return false;
    if (filterMinScore && (s.overall_score || 0) < parseFloat(filterMinScore)) return false;
    if (filterYear && !(s.year || "").toString().includes(filterYear)) return false;
    if (filterTargetRole && !(s.target_role || "").toLowerCase().includes(filterTargetRole.toLowerCase())) return false;
    if (filterCoeVerified && s.coe_status !== "approved") return false;
    if (filterMinSkills) {
      const clearedCount = Object.values(s.skills_summary || {}).filter((v: any) => v && typeof v === "object" && v.status === "coe_verified").length;
      if (clearedCount < parseInt(filterMinSkills)) return false;
    }
    return true;
  });

  const tabs: { key: Tab; label: string; count?: number }[] = [
    { key: "pending", label: "Pending", count: pending.length },
    { key: "approved", label: "Approved", count: approved.length },
    { key: "flagged", label: "Flagged Assessments", count: flaggedAttempts.length || undefined },
    { key: "drives", label: "Placement Drives", count: drives.length || undefined },
  ];

  return (
    <div className="min-h-screen bg-gray-50">
      <div className="sticky top-0 z-30 bg-white/95 backdrop-blur border-b border-gray-200 px-4 py-3 flex items-center gap-3 shadow-sm">
        <ShieldCheck className="w-5 h-5 text-indigo-500" />
        <span className="font-bold text-gray-900 flex-1">COE Verification Dashboard</span>
        <span className="text-xs text-gray-400">ADYPU · 2025 Batch</span>
      </div>

      <div className="max-w-5xl mx-auto px-4 py-6 space-y-5">
        {/* SPCR Readiness Funnel */}
        {funnel && (
          <Card className="bg-gradient-to-br from-indigo-50 to-purple-50 border-indigo-200">
            <CardContent className="p-4">
              <div className="flex items-center gap-2 mb-3">
                <TrendingUp className="w-4 h-4 text-indigo-600" />
                <span className="text-sm font-bold text-indigo-900">SPCR Readiness Funnel</span>
              </div>
              <div className="grid grid-cols-6 gap-2">
                {[
                  { label: "Enrolled", value: funnel.enrolled, color: "text-gray-700" },
                  { label: "Started", value: funnel.started, color: "text-blue-700" },
                  { label: "L1 ✓", value: funnel.l1_passed, color: "text-cyan-700" },
                  { label: "L2 ✓", value: funnel.l2_passed, color: "text-purple-700" },
                  { label: "L3 ✓", value: funnel.l3_passed, color: "text-pink-700" },
                  { label: "Eligible", value: funnel.eligible, color: "text-green-700" },
                ].map(({ label, value, color }) => (
                  <div key={label} className="bg-white rounded-lg p-2 text-center border border-indigo-100">
                    <div className={`text-lg font-black ${color}`}>{value}</div>
                    <div className="text-[10px] text-gray-500 mt-0.5">{label}</div>
                  </div>
                ))}
              </div>
              {funnel.enrolled > 0 && (
                <p className="text-[10px] text-indigo-600 mt-2 text-center">
                  Conversion: {Math.round((funnel.eligible / funnel.enrolled) * 100)}% enrolled → eligible
                </p>
              )}
            </CardContent>
          </Card>
        )}

        {/* KPI strip */}
        <div className="grid grid-cols-3 gap-3">
          {[
            { label: "Total Shortlisted", value: students.length, color: "text-indigo-600" },
            { label: "Pending Verification", value: pending.length, color: "text-amber-600" },
            { label: "Approved", value: approved.length, color: "text-green-600" },
          ].map(({ label, value, color }) => (
            <Card key={label} className="bg-white border-gray-200">
              <CardContent className="p-4 text-center">
                <div className={`text-2xl font-black ${color}`}>{value}</div>
                <div className="text-xs text-gray-500 mt-0.5">{label}</div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Tabs */}
        <div className="flex items-center gap-1 bg-gray-100 rounded-xl p-1 flex-wrap">
          {tabs.map(t => (
            <button
              key={t.key}
              onClick={() => setActiveTab(t.key)}
              className={`px-3 py-2 rounded-lg text-sm font-semibold transition-colors ${activeTab === t.key ? "bg-white text-gray-900 shadow-sm" : "text-gray-500 hover:text-gray-800"}`}
            >
              {t.label}{t.count !== undefined ? ` (${t.count})` : ""}
            </button>
          ))}
        </div>

        {/* ── Student list tabs (pending / approved) ── */}
        {(activeTab === "pending" || activeTab === "approved") && (
          <>
            {/* Filters */}
            <Card className="bg-white border-gray-200">
              <CardContent className="p-3 space-y-2">
                <div className="flex items-center gap-2">
                  <Filter className="w-3.5 h-3.5 text-gray-400" />
                  <span className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Filters</span>
                </div>
                <div className="flex flex-wrap items-center gap-2">
                  <Input placeholder="Branch (CSE, IT…)" value={filterBranch} onChange={e => setFilterBranch(e.target.value)} className="h-8 text-xs w-36" />
                  <Input placeholder="Min score %" type="number" value={filterMinScore} onChange={e => setFilterMinScore(e.target.value)} className="h-8 text-xs w-28" />
                  <Input placeholder="Year (e.g. 2025)" value={filterYear} onChange={e => setFilterYear(e.target.value)} className="h-8 text-xs w-28" />
                  <Input placeholder="Target role" value={filterTargetRole} onChange={e => setFilterTargetRole(e.target.value)} className="h-8 text-xs w-32" />
                  <Input placeholder="Min skills cleared" type="number" value={filterMinSkills} onChange={e => setFilterMinSkills(e.target.value)} className="h-8 text-xs w-32" />
                  <button
                    onClick={() => setFilterCoeVerified(v => !v)}
                    className={`flex items-center gap-1 px-2 py-1 text-xs font-semibold rounded-lg border transition-colors ${filterCoeVerified ? "bg-green-100 border-green-300 text-green-800" : "bg-white border-gray-200 text-gray-500"}`}
                  >
                    <ShieldCheck className="w-3 h-3" /> COE Verified
                  </button>
                  {(filterBranch || filterMinScore || filterYear || filterTargetRole || filterCoeVerified || filterMinSkills) && (
                    <Button size="sm" variant="ghost" onClick={() => { setFilterBranch(""); setFilterMinScore(""); setFilterYear(""); setFilterTargetRole(""); setFilterCoeVerified(false); setFilterMinSkills(""); }} className="text-xs h-8">
                      <X className="w-3 h-3 mr-1" /> Clear
                    </Button>
                  )}
                  <span className="text-xs text-gray-400 ml-auto">{activeList.length} of {baseList.length}</span>
                  <button onClick={() => exportCSV(activeList)} className="flex items-center gap-1 px-3 py-1.5 text-xs font-semibold text-gray-600 border border-gray-200 rounded-lg bg-white hover:bg-gray-50">
                    <Download className="w-3.5 h-3.5" /> CSV
                  </button>
                </div>
              </CardContent>
            </Card>

            {/* Bulk action bar */}
            {selectedUids.size > 0 && activeTab === "pending" && (
              <Card className="bg-amber-50 border-amber-200">
                <CardContent className="p-3 space-y-2">
                  <div className="flex items-center gap-2 text-xs font-bold text-amber-900">
                    <CheckSquare className="w-3.5 h-3.5" /> {selectedUids.size} student{selectedUids.size > 1 ? "s" : ""} selected
                  </div>
                  <div className="flex flex-wrap items-center gap-2">
                    <Input placeholder="Reason (required for flag/proof)" value={bulkReason} onChange={e => setBulkReason(e.target.value)} className="h-8 text-xs flex-1 min-w-[200px]" />
                    <Button size="sm" onClick={() => performBulkAction("approve")} disabled={!!acting} className="bg-green-600 hover:bg-green-700 text-white text-xs h-8">Bulk Approve</Button>
                    <Button size="sm" variant="outline" onClick={() => performBulkAction("flag")} disabled={!!acting} className="border-amber-300 text-amber-700 text-xs h-8">Bulk Flag</Button>
                    <Button size="sm" variant="outline" onClick={() => performBulkAction("request_proof")} disabled={!!acting} className="border-purple-300 text-purple-700 text-xs h-8">Request Docs</Button>
                    <Button size="sm" variant="ghost" onClick={() => setSelectedUids(new Set())} className="text-xs h-8 text-gray-500">Clear</Button>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Student list */}
            {activeList.length === 0 ? (
              <Card className="bg-white border-gray-200">
                <CardContent className="p-10 text-center text-gray-400 text-sm">No students in this category.</CardContent>
              </Card>
            ) : (
              <div className="space-y-3">
                {activeList.map(student => {
                  const isExpanded = expandedRow === student.uid;
                  const cgpaReported = student.cgpa_self_reported || 0;
                  const cgpaVerified = parseFloat(verifiedCGPA[student.uid] || "0");
                  const cgpaMismatch = cgpaVerified > 0 && Math.abs(cgpaVerified - cgpaReported) > 0.3;
                  const cgpaMatch = cgpaVerified > 0 && !cgpaMismatch;
                  const ledger = ledgerData[student.uid];
                  const isLedgerLoading = ledgerLoading[student.uid];

                  return (
                    <Card key={student.uid} className="bg-white border-gray-200 overflow-hidden">
                      <div className="flex items-center gap-3 px-4 py-4 hover:bg-gray-50 transition-colors">
                        {activeTab === "pending" && (
                          <button type="button" onClick={e => { e.stopPropagation(); toggleSelect(student.uid); }} className="flex-shrink-0 text-indigo-600">
                            {selectedUids.has(student.uid) ? <CheckSquare className="w-4 h-4" /> : <Square className="w-4 h-4" />}
                          </button>
                        )}
                        <button type="button" className="flex-1 min-w-0 text-left" onClick={() => setExpandedRow(isExpanded ? null : student.uid)}>
                          <div className="flex items-center gap-2 flex-wrap">
                            <span className="font-semibold text-gray-900 text-sm">{student.name || student.email}</span>
                            <Badge className={`border text-[10px] px-2 py-0.5 ${COE_STATUS_STYLES[student.coe_status] || "bg-gray-100 text-gray-600 border-gray-200"}`}>
                              {COE_STATUS_LABELS[student.coe_status] || student.coe_status}
                            </Badge>
                            {(student.flag_count || 0) > 0 && (
                              <span className="text-[10px] bg-red-50 text-red-600 border border-red-200 px-2 py-0.5 rounded-full font-semibold">⚠️ {student.flag_count} flag{student.flag_count > 1 ? "s" : ""}</span>
                            )}
                          </div>
                          <div className="text-xs text-gray-500 mt-0.5 flex items-center gap-3 flex-wrap">
                            <span>{student.branch}</span>
                            {student.year && <span>Year {student.year}</span>}
                            {student.target_role && <span className="italic">{student.target_role}</span>}
                            <span>CGPA: {cgpaReported}</span>
                            <span className="font-semibold text-indigo-600">{student.credits_earned || 0}/{student.credits_total || 0} credits ({student.overall_score}%)</span>
                            {student.coding_score != null && (
                              <span className="font-semibold text-emerald-600" data-testid={`text-coding-score-${student.uid}`}>Coding: {student.coding_score}%</span>
                            )}
                          </div>
                        </button>
                        <button type="button" title="Print transcript" onClick={e => { e.stopPropagation(); printStudentPage(student); }} className="flex-shrink-0 p-1.5 rounded-md hover:bg-purple-50 text-purple-600">
                          <Printer className="w-4 h-4" />
                        </button>
                        <button type="button" title="Download transcript JSON" onClick={async e => {
                          e.stopPropagation();
                          try {
                            const r = await apiFetch(`/api/placement/transcript/${student.uid}`);
                            if (!r.ok) throw new Error("Failed");
                            const data = await r.json();
                            const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
                            const url = URL.createObjectURL(blob);
                            const a = document.createElement("a"); a.href = url;
                            a.download = `transcript_${(student.name || student.uid).replace(/\s+/g, "_")}.json`;
                            a.click(); URL.revokeObjectURL(url);
                          } catch { toast({ title: "Download failed", variant: "destructive" }); }
                        }} className="flex-shrink-0 p-1.5 rounded-md hover:bg-indigo-50 text-indigo-600">
                          <FileText className="w-4 h-4" />
                        </button>
                        <button type="button" onClick={() => setExpandedRow(isExpanded ? null : student.uid)} className="flex-shrink-0 p-1 text-gray-400 hover:text-gray-600">
                          {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                        </button>
                      </div>

                      {isExpanded && (
                        <div className="border-t border-gray-100 px-4 py-4 space-y-5 bg-gray-50">
                          {/* Skills summary */}
                          {student.skills_summary && Object.keys(student.skills_summary).length > 0 && (
                            <section>
                              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">Self-Reported Skill Completion</p>
                              <p className="text-[11px] text-gray-500 mb-2">⚠️ Verify each skill against course completion certificates or internal exams before approving.</p>
                              <div className="grid sm:grid-cols-2 gap-2">
                                {Object.entries(student.skills_summary).map(([skill, v]: [string, any]) => {
                                  const isObj = v && typeof v === "object";
                                  const status = isObj ? v.status : "self_completed";
                                  const credEarned = isObj ? (v.credits_earned || 0) : 0;
                                  const credTotal = isObj ? (v.credits_total || 0) : 0;
                                  const STATUS_COLOR: Record<string, string> = {
                                    not_started: "text-gray-400 bg-gray-50",
                                    learning: "text-blue-700 bg-blue-50",
                                    self_completed: "text-amber-700 bg-amber-50",
                                    coe_verified: "text-green-700 bg-green-50",
                                  };
                                  return (
                                    <div key={skill} className={`flex items-center justify-between rounded-lg px-3 py-2 border border-gray-200 ${STATUS_COLOR[status] || "bg-white"}`}>
                                      <div className="flex-1 min-w-0">
                                        <div className="text-xs font-medium truncate">{skill}</div>
                                        <div className="text-[10px] opacity-75">{status.replace(/_/g, " ")} · {credEarned}/{credTotal} cr</div>
                                      </div>
                                      {!isObj && <span className="text-xs font-bold ml-2">{v}%</span>}
                                    </div>
                                  );
                                })}
                              </div>
                            </section>
                          )}

                          {/* Per-student Credit Ledger (T007) */}
                          <section>
                            <div className="flex items-center justify-between mb-2">
                              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider">Credit Ledger</p>
                              {!ledger && (
                                <Button size="sm" variant="outline" onClick={() => loadLedger(student.uid)} disabled={isLedgerLoading} className="text-xs h-7 gap-1">
                                  {isLedgerLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Eye className="w-3 h-3" />} View Ledger
                                </Button>
                              )}
                            </div>
                            {ledger && (
                              <div className="overflow-x-auto rounded-lg border border-gray-200">
                                <table className="w-full text-xs">
                                  <thead className="bg-gray-100">
                                    <tr>
                                      <th className="px-3 py-2 text-left font-semibold text-gray-600">Skill</th>
                                      <th className="px-3 py-2 text-center font-semibold text-gray-600">L1</th>
                                      <th className="px-3 py-2 text-center font-semibold text-gray-600">L2</th>
                                      <th className="px-3 py-2 text-center font-semibold text-gray-600">L3</th>
                                      <th className="px-3 py-2 text-right font-semibold text-gray-600">Total Credits</th>
                                    </tr>
                                  </thead>
                                  <tbody>
                                    {(ledger.skills || []).map((sk: any) => {
                                      const lvls = sk.levels || {};
                                      const l1 = lvls.level_1;
                                      const l2 = lvls.level_2;
                                      const l3 = lvls.level_3;
                                      const totalCr = [l1, l2, l3].reduce((sum: number, l: any) => sum + (l?.passed ? (l.credits || 0) : 0), 0);
                                      const cell = (l: any) => l?.passed ? <span className="text-green-600 font-bold">✓ {l.credits || 0}cr</span> : <span className="text-gray-400">—</span>;
                                      return (
                                        <tr key={sk.skill_key} className="border-t border-gray-100 hover:bg-gray-50">
                                          <td className="px-3 py-2 font-medium text-gray-800">{sk.skill || sk.skill_key.replace(/_/g, " ")}</td>
                                          <td className="px-3 py-2 text-center">{cell(l1)}</td>
                                          <td className="px-3 py-2 text-center">{cell(l2)}</td>
                                          <td className="px-3 py-2 text-center">{cell(l3)}</td>
                                          <td className="px-3 py-2 text-right font-bold text-indigo-600">{totalCr}cr</td>
                                        </tr>
                                      );
                                    })}
                                    {(ledger.skills || []).length === 0 && (
                                      <tr><td colSpan={5} className="px-3 py-4 text-center text-gray-400">No skill records yet.</td></tr>
                                    )}
                                  </tbody>
                                </table>
                                <div className="px-3 py-2 bg-gray-50 border-t border-gray-100 flex justify-between text-xs text-gray-500">
                                  <span>{(ledger.attempts || []).length} total attempts</span>
                                  <span>Generated: {ledger.generated_at ? new Date(ledger.generated_at).toLocaleDateString() : "—"}</span>
                                </div>
                              </div>
                            )}
                          </section>

                          {/* CGPA Verification */}
                          <section>
                            <p className="text-xs font-semibold text-gray-500 uppercase tracking-wider mb-2">CGPA Verification</p>
                            <div className="flex items-center gap-3 flex-wrap">
                              <div className="bg-white border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-700">
                                Self-reported: <span className="font-bold">{cgpaReported}</span>
                              </div>
                              <input type="number" min="0" max="10" step="0.1" placeholder="Official CGPA"
                                value={verifiedCGPA[student.uid] || ""}
                                onChange={e => setVerifiedCGPA(prev => ({ ...prev, [student.uid]: e.target.value }))}
                                className="w-36 bg-white border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-indigo-400"
                              />
                              {cgpaMatch && <span className="text-xs text-green-600 font-semibold flex items-center gap-1"><CheckCircle2 className="w-3.5 h-3.5" /> CGPA matches</span>}
                              {cgpaMismatch && <span className="text-xs text-red-600 font-semibold flex items-center gap-1"><XCircle className="w-3.5 h-3.5" /> Discrepancy: reported {cgpaReported}, verified {cgpaVerified}</span>}
                            </div>
                          </section>

                          {/* Action buttons */}
                          {activeTab === "pending" && (
                            <div className="flex gap-2 flex-wrap pt-1">
                              <Button size="sm" onClick={() => performAction(student.uid, "approve")} disabled={!!acting} className="bg-green-600 hover:bg-green-700 text-white text-xs">
                                {acting === student.uid + "approve" ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" /> : <CheckCircle2 className="w-3.5 h-3.5 mr-1" />}
                                Approve for Placement
                              </Button>
                              <Button size="sm" variant="outline" onClick={() => performAction(student.uid, "flag")} disabled={!!acting} className="border-amber-300 text-amber-700 hover:bg-amber-50 text-xs">
                                {acting === student.uid + "flag" ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" /> : <AlertTriangle className="w-3.5 h-3.5 mr-1" />}
                                Flag — Discrepancy
                              </Button>
                              <Button size="sm" variant="outline" onClick={() => performAction(student.uid, "request_proof")} disabled={!!acting} className="border-blue-300 text-blue-700 hover:bg-blue-50 text-xs">
                                {acting === student.uid + "request_proof" ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" /> : <BookOpen className="w-3.5 h-3.5 mr-1" />}
                                Request Supporting Docs
                              </Button>
                              <Button size="sm" variant="outline" onClick={() => performAction(student.uid, "retake")} disabled={!!acting} className="border-purple-300 text-purple-700 hover:bg-purple-50 text-xs">
                                {acting === student.uid + "retake" ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" /> : <Clock className="w-3.5 h-3.5 mr-1" />}
                                Return — Retake Required
                              </Button>
                            </div>
                          )}
                        </div>
                      )}
                    </Card>
                  );
                })}
              </div>
            )}
          </>
        )}

        {/* ── Flagged Assessments tab (T007) ── */}
        {activeTab === "flagged" && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-sm text-gray-600">Skill attempts flagged for integrity review or requiring COE approval (Level 3 submissions).</p>
              <Button size="sm" variant="outline" onClick={loadFlaggedAttempts} disabled={flaggedLoading} className="text-xs gap-1">
                {flaggedLoading ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : null} Refresh
              </Button>
            </div>
            {flaggedLoading ? (
              <Card className="bg-white border-gray-200"><CardContent className="p-8 text-center"><Loader2 className="w-6 h-6 animate-spin mx-auto text-indigo-500" /></CardContent></Card>
            ) : flaggedAttempts.length === 0 ? (
              <Card className="bg-white border-gray-200"><CardContent className="p-10 text-center text-gray-400 text-sm">No flagged assessments pending review.</CardContent></Card>
            ) : (
              <div className="space-y-3">
                {flaggedAttempts.map(attempt => (
                  <Card key={attempt.doc_id} className="bg-white border-gray-200 overflow-hidden">
                    <CardContent className="p-4">
                      <div className="flex items-start gap-3 flex-wrap">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap mb-1">
                            <span className="font-semibold text-gray-900 text-sm">{attempt.skill} — Level {attempt.level}</span>
                            <Badge className="bg-red-50 text-red-700 border-red-200 text-[10px]">Needs Review</Badge>
                            {attempt.integrity_flagged && <Badge className="bg-amber-50 text-amber-700 border-amber-200 text-[10px]">Integrity Flag</Badge>}
                          </div>
                          <div className="text-xs text-gray-500 flex flex-wrap gap-3">
                            <span>Student UID: <span className="font-mono text-gray-700">{attempt.uid}</span></span>
                            <span>Score: <span className="font-semibold text-indigo-600">{attempt.score ?? "—"}%</span></span>
                            <span>Passed: <span className={attempt.passed ? "text-green-600 font-semibold" : "text-red-500 font-semibold"}>{attempt.passed ? "Yes" : "No"}</span></span>
                            {attempt.credits_on_pass > 0 && <span>Credits: {attempt.credits_on_pass}</span>}
                            {attempt.submitted_at && <span>{new Date(attempt.submitted_at).toLocaleDateString()}</span>}
                          </div>
                          {attempt.flag_reasons?.length > 0 && (
                            <div className="mt-2 flex flex-wrap gap-1">
                              {attempt.flag_reasons.map((r: string, i: number) => (
                                <span key={i} className="text-[10px] bg-amber-50 text-amber-700 border border-amber-200 px-2 py-0.5 rounded-full">{r.replace(/_/g, " ")}</span>
                              ))}
                            </div>
                          )}
                        </div>
                        <div className="flex gap-2 flex-shrink-0">
                          <Button
                            size="sm"
                            onClick={() => resolveFlagged(attempt.uid, attempt.doc_id, "approve_credits")}
                            disabled={!!acting || !attempt.passed}
                            className="bg-green-600 hover:bg-green-700 text-white text-xs"
                            title={!attempt.passed ? "Student did not pass — cannot award credits" : ""}
                          >
                            {acting === `flagged_${attempt.doc_id}_approve_credits` ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <CheckCircle2 className="w-3.5 h-3.5 mr-1" />}
                            Approve Credits
                          </Button>
                          <Button
                            size="sm" variant="outline"
                            onClick={() => resolveFlagged(attempt.uid, attempt.doc_id, "dismiss")}
                            disabled={!!acting}
                            className="border-gray-300 text-gray-600 text-xs"
                          >
                            {acting === `flagged_${attempt.doc_id}_dismiss` ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <X className="w-3.5 h-3.5 mr-1" />}
                            Dismiss
                          </Button>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </div>
        )}

        {/* ── Placement Drives tab (T006) ── */}
        {activeTab === "drives" && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <p className="text-sm text-gray-600">Create placement drives — auto-shortlist approved students by criteria and send invite notifications.</p>
              <Button size="sm" onClick={() => setShowDriveForm(v => !v)} className="bg-indigo-600 hover:bg-indigo-700 text-white text-xs gap-1">
                <Plus className="w-3.5 h-3.5" /> New Drive
              </Button>
            </div>

            {/* Drive creation form */}
            {showDriveForm && (
              <Card className="bg-indigo-50 border-indigo-200">
                <CardContent className="p-4 space-y-3">
                  <p className="text-sm font-bold text-indigo-900 flex items-center gap-2"><Building2 className="w-4 h-4" /> Create Placement Drive</p>
                  <div className="grid sm:grid-cols-2 gap-3">
                    <div>
                      <Label className="text-xs font-semibold text-gray-600">Drive Title *</Label>
                      <Input placeholder="e.g. Google SDE-1 Campus Drive 2025" value={driveForm.title} onChange={e => setDriveForm(f => ({ ...f, title: e.target.value }))} className="h-8 text-xs mt-1" />
                    </div>
                    <div>
                      <Label className="text-xs font-semibold text-gray-600">Company *</Label>
                      <Input placeholder="e.g. Google" value={driveForm.company} onChange={e => setDriveForm(f => ({ ...f, company: e.target.value }))} className="h-8 text-xs mt-1" />
                    </div>
                    <div>
                      <Label className="text-xs font-semibold text-gray-600">Drive Date</Label>
                      <Input type="date" value={driveForm.date} onChange={e => setDriveForm(f => ({ ...f, date: e.target.value }))} className="h-8 text-xs mt-1" />
                    </div>
                    <div>
                      <Label className="text-xs font-semibold text-gray-600">Branch Filter</Label>
                      <Input placeholder="e.g. CSE (leave blank for all)" value={driveForm.branch_filter} onChange={e => setDriveForm(f => ({ ...f, branch_filter: e.target.value }))} className="h-8 text-xs mt-1" />
                    </div>
                    <div>
                      <Label className="text-xs font-semibold text-gray-600">Min Readiness Score (%)</Label>
                      <Input type="number" placeholder="0" value={driveForm.min_score} onChange={e => setDriveForm(f => ({ ...f, min_score: e.target.value }))} className="h-8 text-xs mt-1" />
                    </div>
                    <div>
                      <Label className="text-xs font-semibold text-gray-600">Min CGPA</Label>
                      <Input type="number" step="0.1" placeholder="0.0" value={driveForm.min_cgpa} onChange={e => setDriveForm(f => ({ ...f, min_cgpa: e.target.value }))} className="h-8 text-xs mt-1" />
                    </div>
                  </div>
                  <p className="text-[11px] text-indigo-700">Auto-shortlisting pulls all <strong>approved</strong> students matching these criteria. You can send invites after creation.</p>
                  <div className="flex gap-2">
                    <Button size="sm" onClick={createDrive} disabled={driveCreating} className="bg-indigo-600 hover:bg-indigo-700 text-white text-xs">
                      {driveCreating ? <Loader2 className="w-3.5 h-3.5 animate-spin mr-1" /> : <BookOpen className="w-3.5 h-3.5 mr-1" />}
                      Create & Auto-Shortlist
                    </Button>
                    <Button size="sm" variant="ghost" onClick={() => { setShowDriveForm(false); setDriveForm(EMPTY_DRIVE); }} className="text-xs">Cancel</Button>
                  </div>
                </CardContent>
              </Card>
            )}

            {/* Drives list */}
            {drivesLoading ? (
              <Card className="bg-white border-gray-200"><CardContent className="p-8 text-center"><Loader2 className="w-6 h-6 animate-spin mx-auto text-indigo-500" /></CardContent></Card>
            ) : drives.length === 0 ? (
              <Card className="bg-white border-gray-200"><CardContent className="p-10 text-center text-gray-400 text-sm">No drives created yet. Click "New Drive" to get started.</CardContent></Card>
            ) : (
              <div className="space-y-3">
                {drives.map(drive => (
                  <Card key={drive.id} className="bg-white border-gray-200">
                    <CardContent className="p-4">
                      <div className="flex items-start gap-3 flex-wrap">
                        <div className="flex-1 min-w-0">
                          <div className="flex items-center gap-2 flex-wrap mb-1">
                            <span className="font-semibold text-gray-900 text-sm">{drive.title}</span>
                            <Badge className={`text-[10px] border px-2 py-0.5 ${drive.status === "invited" ? "bg-green-50 text-green-700 border-green-200" : "bg-gray-100 text-gray-600 border-gray-200"}`}>
                              {drive.status === "invited" ? "Invites Sent ✓" : "Draft"}
                            </Badge>
                          </div>
                          <div className="text-xs text-gray-500 flex flex-wrap gap-3">
                            <span className="font-medium text-gray-700">{drive.company}</span>
                            {drive.date && <span>{new Date(drive.date).toLocaleDateString()}</span>}
                            <span className="text-indigo-600 font-semibold">{drive.shortlisted_count || 0} shortlisted</span>
                            {drive.invited_count > 0 && <span className="text-green-600">{drive.invited_count} invited</span>}
                            {drive.min_score > 0 && <span>Min score: {drive.min_score}%</span>}
                            {drive.min_cgpa > 0 && <span>Min CGPA: {drive.min_cgpa}</span>}
                            {drive.branch_filter && <span>Branch: {drive.branch_filter}</span>}
                          </div>
                        </div>
                        <Button
                          size="sm"
                          onClick={() => inviteDrive(drive.id)}
                          disabled={!!inviting || (drive.shortlisted_count || 0) === 0}
                          className="bg-indigo-600 hover:bg-indigo-700 text-white text-xs flex-shrink-0 gap-1"
                          title={(drive.shortlisted_count || 0) === 0 ? "No students shortlisted" : ""}
                        >
                          {inviting === drive.id ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Send className="w-3.5 h-3.5" />}
                          Send Invites
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
